/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    tenants: Tenant;
    files: File;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  onboarding?: {
    persona?: ("student" | "professional" | "noJob") | null;
    industry?: string;
    targetRole?: {
      level?: string;
      role?: string;
    };
    // targetRole?: ('projectManager' | 'seniorSoftwareDeveloper') | null;
    challenge?:
      | (
          | "nervousness"
          | "structuringAnswers"
          | "eyeContact"
          | "speakingClearly"
          | "unexpectedQuestions"
          | "relevantExperience"
          | "culturalBarriers"
          | "articulatingComplexIdeas"
          | "focusUnderPressure"
          | "nonVerbalCommunication"
          | "other"
        )[]
      | null;
    goal?: string;
    trainingPlan?: {
      trainingType?: ("structured" | "freestyle") | null;
      hours?: number | null;
      mins?: number | null;
      per?: ("day" | "week" | "month") | null;
    };
    interviewDate?: string | null;
    cv?: string | File | null;
  };
  tenants?:
    | {
        tenant?: (string | null) | Tenant;
        role?: ("owner" | "staff") | null;
        id?: string | null;
      }[]
    | null;
  roles?: ("platform-admin" | "platform-user") | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
  social: {
    issuer: "google" | "facebook" | "linkedin" | "";
    userId: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: string;
  tenant?: (string | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  parent?: (string | null) | Tenant;
  name: string;
  slug: string;
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  fromName?: string;
  fromAddress?: string;
  transportOptions: {
    host: string;
    port: number;
    user: string;
    pass: string;
    secure?: boolean | null;
  };
  template?: {
    [k: string]: unknown;
  }[];
  languages?: "en"[] | null;
  status?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
